#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

#
# Jekyll basic configurations
#

source:         _app
destination:    _site
timezone:       Australia/Sydney
permalink:      /:title.html
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]
exclude:        ["_pages/themes"]

#
# Jekyll serve settings
#

port:           4321

#
# Jekyll build settings
#

future:         false

#
# Additional Markdown settings
#

kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true

redcarpet:
  extensions:
    - footnotes
    - no_intra_emphasis
    - smart
    - space_after_headers
    - strikethrough
    - superscript
    - tables

#
# Jekyll plugins
#

gems:
  - jekyll-last-modified-at

#
# Almace Scaffolding settings
#

# Site name
name: kapalhq.io

# Site description, will appear in the document meta and Atom feed subtitle
description: Building containers for the enterprise

# Base URL, this is useful when I need to build site in a subdirectory (like GitHub Pages for Projects), it provides a specific URL prefix, for example, if the production site URL is http://sparanoid.com/lab/version/, set `base` to `/lab/version/24`, without trailing slash.
# Default:      null
base:           null

# CSS path used in templates
# Default:      /assets
assets:         /assets

# Define feed path. If you use `/feed/index.xml` as feed permalink, `{{ page.url }}` won't pass feed validation with "Self reference doesn't match document location" error
# Default:      /feed.xml
feed:           /feed.xml

# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full URLs for these fields
url:            http://kapalhq.com

# Media assets URL used in posts, without trailing slash. ie. `<img src="{{ site.file }}/image.png">`. In the most cases this URL should be powered by a CDN provider
file:           //d349cztnlupsuf.cloudfront.net

# Download files URL used in posts, ie. href="{{ site.download }}/package.zip", this should also be a CDN link just like `site.url`. There's no differences in `site.url` and `site.download`, I just use one CDN for post images and another for large download files. That's it. Remove or ignore this if you don't need it
download:       http://dl.sparanoid.com

# Google Analytics tracking code
google_analytics:
  enabled:      false
  id:           UA-xxxxxxx
  url:          //www.google-analytics.com/analytics.js

# Site Twitter account handle
twitter:        kapalhq

# Force UTF-8 encoding, enable this will simply add <meta charset="utf-8"> to the head of your pages
# Default:      false
force_utf_8:    false

# Enable this settings to make your feed Daring Fireball-like link blog
# (This basically change your <link> value to external link you defined in your posts)
# Default:      false
link_blog:      false

# Change the value to true to use post excerpt for RSS feeds
# Default:      false
rss_excerpt:    false

# Show generator credits
# Default:      true
credits:        true

#
# Custom distribution variables
#

# SSH remote server hostname
remote_host:    caladbolg

# Prevent them from being deleted on server (rsync --delete), these files and directories are available on the remote server but outside this git repo. I need to ignore them.
ignore_files:   --exclude=lab

# Media assets sync'ed using s3cmd
static_files:   ~/Workspace/Sites/static.sparanoid.com/

# Remote server root directory
remote_dir:     /srv/www/sparanoid.com/public_html

# Amazon S3 Bucket variable for s3cmd
s3_bucket:      s3://sparanoid/
